export const colors = {
  background: '#141314',
  surface: '#141314',
  surfaceDim: '#141314',
  surfaceBright: '#3b393a',
  surfaceContainerLowest: '#0f0e0f',
  surfaceContainerLow: '#1d1b1c',
  surfaceContainer: '#211f20',
  surfaceContainerHigh: '#2b292a',
  surfaceContainerHighest: '#363435',
  surfaceVariant: '#363435',
  onSurface: '#e6e1e2',
  onSurfaceVariant: '#e0bec8',
  inverseSurface: '#e6e1e2',
  inverseOnSurface: '#323031',
  primary: '#ffb0cc',
  onPrimary: '#640038',
  primaryContainer: '#d72483',
  onPrimaryContainer: '#fffaf9',
  inversePrimary: '#b8006c',
  primaryFixed: '#ffd9e4',
  primaryFixedDim: '#ffb0cc',
  onPrimaryFixed: '#3e0021',
  onPrimaryFixedVariant: '#8d0052',
  secondary: '#ffb1c2',
  onSecondary: '#66002b',
  secondaryContainer: '#c8035c',
  onSecondaryContainer: '#ffdbe1',
  secondaryFixed: '#ffd9df',
  secondaryFixedDim: '#ffb1c2',
  onSecondaryFixed: '#3f0018',
  onSecondaryFixedVariant: '#8f0040',
  tertiary: '#ffafd8',
  onTertiary: '#5e0943',
  tertiaryContainer: '#b2528a',
  onTertiaryContainer: '#fffafa',
  tertiaryFixed: '#ffd8e9',
  tertiaryFixedDim: '#ffafd8',
  onTertiaryFixed: '#3c0029',
  onTertiaryFixedVariant: '#7b255b',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  outline: '#a78992',
  outlineVariant: '#584048',
  surfaceTint: '#ffb0cc',
  onBackground: '#e6e1e2',
};

export const typography = {
  displayLg: {
    fontFamily: 'Montserrat',
    fontSize: '56px',
    fontWeight: '700',
    lineHeight: '1.1',
    letterSpacing: '-0.02em',
  },
  headlineLg: {
    fontFamily: 'Montserrat',
    fontSize: '32px',
    fontWeight: '700',
    lineHeight: '1.2',
  },
  headlineLgMobile: {
    fontFamily: 'Montserrat',
    fontSize: '24px',
    fontWeight: '700',
    lineHeight: '1.2',
  },
  headlineMd: {
    fontFamily: 'Montserrat',
    fontSize: '24px',
    fontWeight: '600',
    lineHeight: '1.3',
  },
  bodyLg: {
    fontFamily: 'Montserrat',
    fontSize: '18px',
    fontWeight: '400',
    lineHeight: '1.6',
  },
  bodyMd: {
    fontFamily: 'Montserrat',
    fontSize: '16px',
    fontWeight: '400',
    lineHeight: '1.6',
  },
  labelLg: {
    fontFamily: 'Montserrat',
    fontSize: '14px',
    fontWeight: '600',
    lineHeight: '1.4',
    letterSpacing: '0.05em',
  },
  labelSm: {
    fontFamily: 'Montserrat',
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '1.4',
    letterSpacing: '0.05em',
  },
};

export const rounded = {
  sm: '0.25rem',
  DEFAULT: '0.5rem',
  md: '0.75rem',
  lg: '1rem',
  xl: '1.5rem',
  full: '9999px',
};

export const spacing = {
  base: '8px',
  xs: '4px',
  sm: '12px',
  md: '24px',
  lg: '48px',
  xl: '80px',
  gutter: '24px',
  marginMobile: '16px',
  marginDesktop: '64px',
};
